name: "Guix Lint Check"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  guix-lint:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Guix (if not already available in the runner)
      - name: Install Guix
        run: |
          cd /tmp
          wget 'https://git.savannah.gnu.org/gitweb/?p=guix.git;a=blob_plain;f=etc/guix-install.sh;hb=HEAD'
          chmod +x guix-install.sh
          ./guix-install.sh

      # 3. Run the guix lint check
      - name: Run Guix Lint
        run: |
          guix lint
